"""add plant_ids to diagnosis and issue

Revision ID: 11c63814d5e7
Revises: b91d4de54f28
Create Date: 2026-03-14 15:44:42.166460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c63814d5e7'
down_revision: Union[str, Sequence[str], None] = 'b91d4de54f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('plant_ids', sa.JSON(), nullable=True))
    op.add_column('issues', sa.Column('plant_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'plant_ids')
    op.drop_column('diagnoses', 'plant_ids')
    # ### end Alembic commands ###
