"""convert care_template fields to sql enum and json for hardiness_zones

Revision ID: 2be105a5fba8
Revises: 705c02fe189f
Create Date: 2026-03-28 15:22:22.672477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be105a5fba8'
down_revision: Union[str, Sequence[str], None] = '705c02fe189f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (lowercase to match existing data)
    lightrequirement = sa.Enum('low', 'medium', 'bright_indirect', 'full_sun', name='lightrequirement')
    soilcondition = sa.Enum('sandy', 'loam', 'clay', 'peat', 'well_draining', 'well_draining_aerated', 'cacti', name='soilcondition')
    lightrequirement.create(op.get_bind(), checkfirst=True)
    soilcondition.create(op.get_bind(), checkfirst=True)

    op.add_column('care_templates', sa.Column('hardiness_zones', sa.JSON(), nullable=True))
    op.alter_column('care_templates', 'light_requirements',
               existing_type=sa.VARCHAR(),
               type_=lightrequirement,
               existing_nullable=True,
               postgresql_using='light_requirements::text::lightrequirement')
    op.alter_column('care_templates', 'soil_conditions',
               existing_type=sa.VARCHAR(),
               type_=soilcondition,
               existing_nullable=True,
               postgresql_using='soil_conditions::text::soilcondition')
    op.drop_column('care_templates', 'hardiness_zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_templates', sa.Column('hardiness_zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    lightrequirement = sa.Enum('low', 'medium', 'bright_indirect', 'full_sun', name='lightrequirement')
    soilcondition = sa.Enum('sandy', 'loam', 'clay', 'peat', 'well_draining', 'well_draining_aerated', 'cacti', name='soilcondition')
    op.alter_column('care_templates', 'soil_conditions',
               existing_type=soilcondition,
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('care_templates', 'light_requirements',
               existing_type=lightrequirement,
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('care_templates', 'hardiness_zones')
    # Drop enum types
    lightrequirement.drop(op.get_bind(), checkfirst=True)
    soilcondition.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
