"""Add unique constraint on user_plant

Revision ID: b91d4de54f28
Revises: 6ae197f0459b
Create Date: 2026-03-13 12:27:13.021984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91d4de54f28'
down_revision: Union[str, Sequence[str], None] = '6ae197f0459b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_plant', 'user_plants', ['user_id', 'plant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_plant', 'user_plants', type_='unique')
    # ### end Alembic commands ###
