"""add watering_schedules table

Revision ID: eed51c6b07a6
Revises: 1e4934a3978b
Create Date: 2026-03-28 17:01:22.742333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed51c6b07a6'
down_revision: Union[str, Sequence[str], None] = '1e4934a3978b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watering_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watering_interval_days', sa.Integer(), nullable=False),
    sa.Column('next_watering_date', sa.DateTime(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_plant_id', name='uq_watering_schedule_user_plant')
    )
    op.create_index(op.f('ix_watering_schedules_id'), 'watering_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_watering_schedules_id'), table_name='watering_schedules')
    op.drop_table('watering_schedules')
    # ### end Alembic commands ###
